version: '2.1'
services:
mysql:    image: mariadb:latest
container_name: mysql_service
volumes:      - ./data/mysql/data:/var/lib/mysql
ports:      - 3306:3306
environment:       - MYSQL_ROOT_PASSWORD=root
redis:    image: redis:alpine
ports:      - 6379:6379
volumes:       - ./data/redis/data:/data
nginx-lb:    build: services/nginx/
ports:      - 80:80
command: >        nginx -g "daemon off;"
